### ISSUE TITLE
一部のブラウザで表のレイアウトが見づらい

### ISSUE THREAD

**Issue by saxAllan** [chirimen-oh/chirimen.org#64]
現状、Edge (44.18362.387.0) で partsList(https://tutorial.chirimen.org/raspi3/partslist) のページを開くと説明部分が改行されず、横スクロールしないと全体が見えない表になってしまう。

IE(11.418.18362.0) や Firefox(69.0.3) でも Edge ほどではないが収まっていない。

※ちなみにChrome(77.0.3865.120) では問題なく表示された。

**Comment by elie-j** [comment]
Firefox でも Partslist が正常に表示されないようです。横スクロールも表示されない状態です。
![Fx-PartslistPageScreenshot_](https://user-images.githubusercontent.com/2101965/69042191-24c9bf00-0a34-11ea-9616-1ee498e71887.png)

**Comment by saxAllan** [comment]
Chromium ベースの Edge (80.0.361.50) では Chrome くらいまでレイアウトは落ち着いた。

**Comment by dynamis** [comment]
問題のブラウザは既にサポート終了しており気にしなくて良い状況になっていると思うので wontfix close してしまいます。

続き？としてはモバイル対応 #131 の中で
