### ISSUE TITLE
配線図の GND 線が足りない

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/chirimen.org#90]
section4 の配線図が MOSFET に GND が配線されてないという指摘を受けました。その通りです！

https://tutorial.chirimen.org/raspi/section4#section-4
https://github.com/chirimen-oh/chirimen.org/blob/master/raspi/imgs/section4/schematic_new.png

指摘画像:
![image](https://user-images.githubusercontent.com/188166/101273839-6282bc80-37dc-11eb-8741-9ac208b3d1a9.png)

**Comment by 100edu** [comment]
差し替え用の画像作りました。SHT30のも作ってみました。
<img width="920" alt="ADT7410Motor" src="https://user-images.githubusercontent.com/38311489/102678361-33f8de80-41eb-11eb-827d-40d2ac0bfbb3.png">
<img width="743" alt="SHT3MOTOR" src="https://user-images.githubusercontent.com/38311489/102678364-3824fc00-41eb-11eb-86bf-e38ead01f300.png">
